### ISSUE TITLE
Global todo list

### ISSUE THREAD

**Issue by Reinisch** [Reinisch/Darkest-Dungeon-Unity#3]
- [x] 1. town events
- [ ] 2. tutorial
- [x] 3. narration and sounds
- [x] 4. predefined maps
- [x] 5. character and dungeon color LuTs
- [ ] 6. finish all dialogues
- [x] 7. add plot quest dungeon slot
- [x] 8. implement statue content
